/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditLog {
  'action' : string,
  'userId' : Principal,
  'locationId' : string,
  'timestamp' : Time,
}
export interface Location { 'id' : string, 'name' : string, 'slug' : string }
export interface Report {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'area' : string,
  'description' : string,
  'locationId' : string,
  'timestamp' : Time,
  'contactEmail' : string,
  'serviceId' : string,
}
export type Role = { 'admin' : null } |
  { 'moderator' : string } |
  { 'user' : null };
export interface Service {
  'id' : string,
  'status' : ServiceStatus,
  'impact' : string,
  'name' : string,
  'locationId' : string,
}
export type ServiceStatus = { 'warning' : null } |
  { 'interrupted' : null } |
  { 'operational' : null };
export type Time = bigint;
export interface User {
  'id' : Principal,
  'name' : string,
  'role' : Role,
  'email' : string,
  'mustChangePassword' : boolean,
}
export interface _SERVICE {
  'addService' : ActorMethod<[string, string, string], undefined>,
  'approveReport' : ActorMethod<[string], undefined>,
  'createLocation' : ActorMethod<[string], undefined>,
  'getAllLocations' : ActorMethod<[], Array<Location>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAuditLogs' : ActorMethod<[string], Array<AuditLog>>,
  'getPendingReports' : ActorMethod<[string], Array<Report>>,
  'getServicesByLocation' : ActorMethod<[string], Array<Service>>,
  'register' : ActorMethod<[string, string], undefined>,
  'rejectReport' : ActorMethod<[string], undefined>,
  'submitReport' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];