/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Location = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'slug' : IDL.Text,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'moderator' : IDL.Text,
  'user' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'mustChangePassword' : IDL.Bool,
});
export const Time = IDL.Int;
export const AuditLog = IDL.Record({
  'action' : IDL.Text,
  'userId' : IDL.Principal,
  'locationId' : IDL.Text,
  'timestamp' : Time,
});
export const Report = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'area' : IDL.Text,
  'description' : IDL.Text,
  'locationId' : IDL.Text,
  'timestamp' : Time,
  'contactEmail' : IDL.Text,
  'serviceId' : IDL.Text,
});
export const ServiceStatus = IDL.Variant({
  'warning' : IDL.Null,
  'interrupted' : IDL.Null,
  'operational' : IDL.Null,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'status' : ServiceStatus,
  'impact' : IDL.Text,
  'name' : IDL.Text,
  'locationId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'approveReport' : IDL.Func([IDL.Text], [], []),
  'createLocation' : IDL.Func([IDL.Text], [], []),
  'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAuditLogs' : IDL.Func([IDL.Text], [IDL.Vec(AuditLog)], ['query']),
  'getPendingReports' : IDL.Func([IDL.Text], [IDL.Vec(Report)], ['query']),
  'getServicesByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectReport' : IDL.Func([IDL.Text], [], []),
  'submitReport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Location = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'slug' : IDL.Text,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'moderator' : IDL.Text,
    'user' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'mustChangePassword' : IDL.Bool,
  });
  const Time = IDL.Int;
  const AuditLog = IDL.Record({
    'action' : IDL.Text,
    'userId' : IDL.Principal,
    'locationId' : IDL.Text,
    'timestamp' : Time,
  });
  const Report = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'area' : IDL.Text,
    'description' : IDL.Text,
    'locationId' : IDL.Text,
    'timestamp' : Time,
    'contactEmail' : IDL.Text,
    'serviceId' : IDL.Text,
  });
  const ServiceStatus = IDL.Variant({
    'warning' : IDL.Null,
    'interrupted' : IDL.Null,
    'operational' : IDL.Null,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'status' : ServiceStatus,
    'impact' : IDL.Text,
    'name' : IDL.Text,
    'locationId' : IDL.Text,
  });
  
  return IDL.Service({
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'approveReport' : IDL.Func([IDL.Text], [], []),
    'createLocation' : IDL.Func([IDL.Text], [], []),
    'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAuditLogs' : IDL.Func([IDL.Text], [IDL.Vec(AuditLog)], ['query']),
    'getPendingReports' : IDL.Func([IDL.Text], [IDL.Vec(Report)], ['query']),
    'getServicesByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectReport' : IDL.Func([IDL.Text], [], []),
    'submitReport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };