/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    id: string;
    name: string;
    slug: string;
}
export interface AuditLog {
    action: string;
    userId: Principal;
    locationId: string;
    timestamp: Time;
}
export type Time = bigint;
export interface User {
    id: Principal;
    name: string;
    role: Role;
    email: string;
    mustChangePassword: boolean;
}
export interface Service {
    id: string;
    status: ServiceStatus;
    impact: string;
    name: string;
    locationId: string;
}
export interface Report {
    id: string;
    status: Variant_pending_approved_rejected;
    area: string;
    description: string;
    locationId: string;
    timestamp: Time;
    contactEmail: string;
    serviceId: string;
}
export type Role = {
    __kind__: "admin";
    admin: null;
} | {
    __kind__: "moderator";
    moderator: string;
} | {
    __kind__: "user";
    user: null;
};
export enum ServiceStatus {
    warning = "warning",
    interrupted = "interrupted",
    operational = "operational"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    addService(locationId: string, name: string, impact: string): Promise<void>;
    approveReport(reportId: string): Promise<void>;
    createLocation(name: string): Promise<void>;
    getAllLocations(): Promise<Array<Location>>;
    getAllUsers(): Promise<Array<User>>;
    getAuditLogs(locationId: string): Promise<Array<AuditLog>>;
    getPendingReports(locationId: string): Promise<Array<Report>>;
    getServicesByLocation(locationId: string): Promise<Array<Service>>;
    register(name: string, email: string): Promise<void>;
    rejectReport(reportId: string): Promise<void>;
    submitReport(locationId: string, serviceId: string, area: string, description: string, contactEmail: string): Promise<void>;
}
import type { Report as _Report, Role as _Role, Service as _Service, ServiceStatus as _ServiceStatus, Time as _Time, User as _User } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addService(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0, arg1, arg2);
            return result;
        }
    }
    async approveReport(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveReport(arg0);
            return result;
        }
    }
    async createLocation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLocation(arg0);
            return result;
        }
    }
    async getAllLocations(): Promise<Array<Location>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLocations();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLogs(arg0: string): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs(arg0);
            return result;
        }
    }
    async getPendingReports(arg0: string): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingReports(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingReports(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServicesByLocation(arg0: string): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicesByLocation(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicesByLocation(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return result;
        }
    }
    async rejectReport(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectReport(arg0);
            return result;
        }
    }
    async submitReport(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReport(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReport(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_Report_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceStatus): ServiceStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_User_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ServiceStatus;
    impact: string;
    name: string;
    locationId: string;
}): {
    id: string;
    status: ServiceStatus;
    impact: string;
    name: string;
    locationId: string;
} {
    return {
        id: value.id,
        status: from_candid_ServiceStatus_n13(_uploadFile, _downloadFile, value.status),
        impact: value.impact,
        name: value.name,
        locationId: value.locationId
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    role: _Role;
    email: string;
    mustChangePassword: boolean;
}): {
    id: Principal;
    name: string;
    role: Role;
    email: string;
    mustChangePassword: boolean;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_Role_n4(_uploadFile, _downloadFile, value.role),
        email: value.email,
        mustChangePassword: value.mustChangePassword
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    area: string;
    description: string;
    locationId: string;
    timestamp: _Time;
    contactEmail: string;
    serviceId: string;
}): {
    id: string;
    status: Variant_pending_approved_rejected;
    area: string;
    description: string;
    locationId: string;
    timestamp: Time;
    contactEmail: string;
    serviceId: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n9(_uploadFile, _downloadFile, value.status),
        area: value.area,
        description: value.description,
        locationId: value.locationId,
        timestamp: value.timestamp,
        contactEmail: value.contactEmail,
        serviceId: value.serviceId
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    interrupted: null;
} | {
    operational: null;
}): ServiceStatus {
    return "warning" in value ? ServiceStatus.warning : "interrupted" in value ? ServiceStatus.interrupted : "operational" in value ? ServiceStatus.operational : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    moderator: string;
} | {
    user: null;
}): {
    __kind__: "admin";
    admin: null;
} | {
    __kind__: "moderator";
    moderator: string;
} | {
    __kind__: "user";
    user: null;
} {
    return "admin" in value ? {
        __kind__: "admin",
        admin: value.admin
    } : "moderator" in value ? {
        __kind__: "moderator",
        moderator: value.moderator
    } : "user" in value ? {
        __kind__: "user",
        user: value.user
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Array<Report> {
    return value.map((x)=>from_candid_Report_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
